$x_i={i\over 100}; i=\overline{0,100}$

In [6]:
def x(i):
    return i/100

In [7]:
[x(i) for i in range(0,101)]

[0.0,
 0.01,
 0.02,
 0.03,
 0.04,
 0.05,
 0.06,
 0.07,
 0.08,
 0.09,
 0.1,
 0.11,
 0.12,
 0.13,
 0.14,
 0.15,
 0.16,
 0.17,
 0.18,
 0.19,
 0.2,
 0.21,
 0.22,
 0.23,
 0.24,
 0.25,
 0.26,
 0.27,
 0.28,
 0.29,
 0.3,
 0.31,
 0.32,
 0.33,
 0.34,
 0.35,
 0.36,
 0.37,
 0.38,
 0.39,
 0.4,
 0.41,
 0.42,
 0.43,
 0.44,
 0.45,
 0.46,
 0.47,
 0.48,
 0.49,
 0.5,
 0.51,
 0.52,
 0.53,
 0.54,
 0.55,
 0.56,
 0.57,
 0.58,
 0.59,
 0.6,
 0.61,
 0.62,
 0.63,
 0.64,
 0.65,
 0.66,
 0.67,
 0.68,
 0.69,
 0.7,
 0.71,
 0.72,
 0.73,
 0.74,
 0.75,
 0.76,
 0.77,
 0.78,
 0.79,
 0.8,
 0.81,
 0.82,
 0.83,
 0.84,
 0.85,
 0.86,
 0.87,
 0.88,
 0.89,
 0.9,
 0.91,
 0.92,
 0.93,
 0.94,
 0.95,
 0.96,
 0.97,
 0.98,
 0.99,
 1.0]

In [8]:
xx = [x(i) for i in range(0,101)]

In [9]:
x

<function __main__.x(i)>

In [10]:
xx

[0.0,
 0.01,
 0.02,
 0.03,
 0.04,
 0.05,
 0.06,
 0.07,
 0.08,
 0.09,
 0.1,
 0.11,
 0.12,
 0.13,
 0.14,
 0.15,
 0.16,
 0.17,
 0.18,
 0.19,
 0.2,
 0.21,
 0.22,
 0.23,
 0.24,
 0.25,
 0.26,
 0.27,
 0.28,
 0.29,
 0.3,
 0.31,
 0.32,
 0.33,
 0.34,
 0.35,
 0.36,
 0.37,
 0.38,
 0.39,
 0.4,
 0.41,
 0.42,
 0.43,
 0.44,
 0.45,
 0.46,
 0.47,
 0.48,
 0.49,
 0.5,
 0.51,
 0.52,
 0.53,
 0.54,
 0.55,
 0.56,
 0.57,
 0.58,
 0.59,
 0.6,
 0.61,
 0.62,
 0.63,
 0.64,
 0.65,
 0.66,
 0.67,
 0.68,
 0.69,
 0.7,
 0.71,
 0.72,
 0.73,
 0.74,
 0.75,
 0.76,
 0.77,
 0.78,
 0.79,
 0.8,
 0.81,
 0.82,
 0.83,
 0.84,
 0.85,
 0.86,
 0.87,
 0.88,
 0.89,
 0.9,
 0.91,
 0.92,
 0.93,
 0.94,
 0.95,
 0.96,
 0.97,
 0.98,
 0.99,
 1.0]

In [11]:
import numpy as np

In [12]:
x3 = np.array(xx)

In [13]:
x3

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [14]:
def y(x):
    return 2*x - 3.1415

In [15]:
y3 = np.array([y(x) for x in x3])

In [16]:
y3

array([-3.1415, -3.1215, -3.1015, -3.0815, -3.0615, -3.0415, -3.0215,
       -3.0015, -2.9815, -2.9615, -2.9415, -2.9215, -2.9015, -2.8815,
       -2.8615, -2.8415, -2.8215, -2.8015, -2.7815, -2.7615, -2.7415,
       -2.7215, -2.7015, -2.6815, -2.6615, -2.6415, -2.6215, -2.6015,
       -2.5815, -2.5615, -2.5415, -2.5215, -2.5015, -2.4815, -2.4615,
       -2.4415, -2.4215, -2.4015, -2.3815, -2.3615, -2.3415, -2.3215,
       -2.3015, -2.2815, -2.2615, -2.2415, -2.2215, -2.2015, -2.1815,
       -2.1615, -2.1415, -2.1215, -2.1015, -2.0815, -2.0615, -2.0415,
       -2.0215, -2.0015, -1.9815, -1.9615, -1.9415, -1.9215, -1.9015,
       -1.8815, -1.8615, -1.8415, -1.8215, -1.8015, -1.7815, -1.7615,
       -1.7415, -1.7215, -1.7015, -1.6815, -1.6615, -1.6415, -1.6215,
       -1.6015, -1.5815, -1.5615, -1.5415, -1.5215, -1.5015, -1.4815,
       -1.4615, -1.4415, -1.4215, -1.4015, -1.3815, -1.3615, -1.3415,
       -1.3215, -1.3015, -1.2815, -1.2615, -1.2415, -1.2215, -1.2015,
       -1.1815, -1.1

In [17]:
from bokeh.io import output_notebook
output_notebook()

Loading BokehJS ...

In [27]:
import bokeh.plotting as bp

In [45]:
fig = bp.figure(plot_width = 400, plot_height = 200)

In [46]:
fig.line(x3,y3)

GlyphRenderer(id='1688', ...)

In [47]:
bp.show(fig)

In [21]:
import numpy.random as npr

In [32]:
npr.randn()

-0.3513224213235954

In [41]:
yn = np.array([x + npr.randn() for x in x3])

In [48]:
fig.circle(x3, yn, size = 5)

GlyphRenderer(id='1800', ...)

In [49]:
bp.show(fig)

In [44]:
yn

array([-8.50739160e-01,  8.77663377e-01, -3.23270424e-01, -3.07875200e-01,
        2.06214492e+00,  2.10869011e-01, -7.63570548e-01, -1.76903562e-01,
        1.32938668e-01,  9.36959903e-01, -1.62532928e+00, -3.22580676e-02,
        1.75029897e+00,  8.56260313e-01,  1.89926869e-01, -4.94616270e-01,
       -2.83887483e-01, -1.20824944e+00,  3.01626382e-01, -8.04901876e-01,
       -1.46391211e+00,  1.64987053e+00,  1.79553004e+00,  2.46103170e-01,
        9.33899530e-02, -8.57792605e-01, -2.29611153e+00, -1.00955391e+00,
       -1.30300134e+00,  5.62496337e-02,  6.20353363e-01,  4.44201444e-01,
       -7.04696707e-01,  2.50860602e+00,  1.32494283e+00,  1.30102822e+00,
        9.99017280e-01,  7.67923800e-01,  6.21293958e-01,  2.28236429e-01,
        2.00250760e+00, -1.64098548e+00, -1.08918339e+00, -9.08631232e-01,
        7.33956522e-01,  9.07531847e-01,  1.47091362e-01, -6.09784810e-01,
        1.35251687e+00, -5.40619624e-01,  2.46086630e-01,  2.51642954e+00,
        2.68566046e-02,  

In [52]:
model = sklm.LinearRegression()

In [51]:
import sklearn.linear_model as sklm

In [54]:
model.fit(np.reshape(x3, (-1,1)), np.reshape(y3, (-1,1)))

LinearRegression()

In [55]:
model.get_params()

{'copy_X': True,
 'fit_intercept': True,
 'n_jobs': None,
 'normalize': False,
 'positive': False}

In [56]:
score(np.reshape(x3, (-1,1)), np.reshape(y3, (-1,1)))

NameError: name 'score' is not defined

In [57]:
model.score(np.reshape(x3, (-1,1)), np.reshape(y3, (-1,1)))

1.0